import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import { Navbar } from "@/components/navbar";
import { cn } from "@/lib/utils";
import { ToggleProvider } from "@/context/toggle";
import "./globals.css";
import Image from "next/image";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "YourBanK | Home",
    template: "YourBanK | %s",
  },
  icons: {
    icon: "/logo.svg",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          lexend.className,
          "bg-shades-grey-10 mx-auto mt-40 lg:mt-0 overflow-x-hidden flex flex-col items-center min-h-screen text-white gap-y-[50px] lg:gap-y-[30px] 2xl:gap-y-[53px]"
        )}
      >
        <Image
          src="/assets/abstract-2.svg"
          alt="Abstract Image 2"
          width={50}
          height={50}
          sizes="auto"
          priority
          className="absolute -z-10 -top-7 -left-7 lg:-top-12 lg:-left-12 w-[25rem] lg:w-[28rem] 2xl:w-[35rem]"
        />
        <ToggleProvider>
          <div className="px-4 lg:px-20 2xl:px-[162px] container mt-12 fixed z-[9999] top-0 lg:static">
            <Navbar />
          </div>
        </ToggleProvider>
        {children}
      </body>
    </html>
  );
}
