import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import { Navbar } from "@/components/navbar";
import { cn } from "@/lib/utils";
import "./globals.css";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "YourBanK | Home",
    template: "YourBanK | %s",
  },
  icons: {
    icon: "/logo.svg",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          lexend.className,
          "bg-shades-grey-10 container mx-auto px-4 lg:px-20 2xl:px-[162px] flex flex-col min-h-screen text-white gap-y-[50px] lg:gap-y-[30px] 2xl:gap-y-[53px]"
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
